### ISSUE TITLE
App stopped While Click on Playlists When we are in offline mode. 

### ISSUE THREAD

**Issue by wanizubair** [nvllsvm/Audinaut#25]
#### Expected behavior
The App should be able to open Playlists when we are in  offline mode. 

#### Actual behavior

The App is not able to open Playlists, when we are in offline mode when we click on Playlists option the app suddenly stops.

#### How to reproduce

+ Download the App. 

+ Launch the App. 

+ Click on Go offline. 

+ Click on Playlists option, the app suddenly stops and would not be able to open Playlists. 

* Application :Audinaut, Version :0.2.5
* Operating system:Android Nougat (7.0)

#### Recording Of The Bug
https://youtu.be/wnpWuG-AgMI    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wanizubair/app-stopped-while-click-on-playlists-when-we-are-in-offline-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dddddd-mmmmmm** [comment]
I could reproduce with 0.5.0, I'll take a look at this.

**Comment by dddddd-mmmmmm** [comment]
Curiously, this issue doesn't occur with Android Virtual Devices.

**Comment by dddddd-mmmmmm** [comment]
`2020-01-23 15:03:53.257 8208-8208/net.nullsum.audinaut E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.nullsum.audinaut, PID: 8208
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter $this$toHttpUrlOrNull
        at okhttp3.HttpUrl$Companion.parse(Unknown Source:2)
        at okhttp3.HttpUrl.parse(Unknown Source:2)
        at net.nullsum.audinaut.util.Util.getRestUrl(Util.java:305)
        at net.nullsum.audinaut.util.Util.getRestUrl(Util.java:298)
        at net.nullsum.audinaut.util.SyncUtil.checkRestURL(SyncUtil.java:18)
        at net.nullsum.audinaut.util.SyncUtil.isSyncedPlaylist(SyncUtil.java:27)
        at net.nullsum.audinaut.view.PlaylistView.updateBackground(PlaylistView.java:62)
        at net.nullsum.audinaut.view.UpdateView.setObject(UpdateView.java:199)
        at net.nullsum.audinaut.adapter.PlaylistAdapter.onBindViewHolder(PlaylistAdapter.java:47)
        at net.nullsum.audinaut.adapter.PlaylistAdapter.onBindViewHolder(PlaylistAdapter.java:27)
        at net.nullsum.audinaut.adapter.SectionAdapter.onBindViewHolder(SectionAdapter.java:157)
        at net.nullsum.audinaut.adapter.SectionAdapter.onBindViewHolder(SectionAdapter.java:49)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1081)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(SlidingUpPanelLayout.java:898)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
2020-01-23 15:03:53.257 8208-8208/net.nullsum.audinaut E/AndroidRuntime:     at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:773)
        at android.view.View.layout(View.java:19654)
        at android.view.ViewGroup.layout(ViewGroup.java:6127)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2581)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2290)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1448)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6691)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)`

**Comment by nvllsvm** [comment]
Fixed in 0.5.1
