### ISSUE TITLE
Add support for p= authentication method

### ISSUE THREAD

**Issue by ehahn** [nvllsvm/Audinaut#26]
The token+salt authentication method requires that the server stores the user's password insecurely in plain text. It does not work with (Sub|Libre|Air)sonic when using LDAP[1] or with Supysonic.

[1] https://github.com/Libresonic/libresonic/issues/69#issuecomment-242216709

**Comment by paulijar** [comment]
To add to this, I have recently added support for Subsonic-compatible server API to ownCloud Music: https://github.com/owncloud/music/pull/718. This implementation, however, does not support the token+salt authentication method. This currently rules out Audinaut as possible client for the ownCloud/Nextcloud users. 

My implementation might be missing also other services needed by Audinaut, but it's hard to tell when the connection cannot be established. If needed, I'm ready to add any other missing services to the server, but the token+salt method is something I'm not planning to support. This is because of the intrinsic unsecurity of this security scheme.

The Subsonic API specification http://www.subsonic.org/pages/api.jsp also contains a dedicated error code 41 for the situations when the server cannot support the token authentication. Hence, the client could fall back to the p= authentication when receiving this error. Another alternative is to have a user setting to select the authentication method.

**Comment by nikolowry** [comment]
Any updates on this? Very unfortunate that the most well maintained Ampache/Subsonic client on F-Droid isn't compatible with @paulijar's app.

**Comment by dddddd-mmmmmm** [comment]
I'll take a look at this.

**Comment by dddddd-mmmmmm** [comment]
I've added an Authentication Method preference which switches between token/salt and password parameters.
I don't have an OwnCloud/LDAP instance myself so if someone could test this that would be great.

I've built a pre-release [available here](https://github.com/dddddd-mmmmmm/Audinaut/releases/tag/issue-26)

**Comment by nikolowry** [comment]
@dddddd-mmmmmm couldn't install the linked apk on my arm64 device. Will try building later and report back

**Comment by nikolowry** [comment]
@dddddd-mmmmmm still getting the same error response after building and installing the Debug variant. Toggling "Authentication Method" had no effect:

![Screenshot_20200113-143223_Audinaut](https://user-images.githubusercontent.com/597310/72285745-c70bba80-3611-11ea-8a4e-c3977954a57d.png)

![Screenshot_20200113-143243_Audinaut](https://user-images.githubusercontent.com/597310/72285763-cecb5f00-3611-11ea-9c07-269d4bf29044.png)

**Comment by paulijar** [comment]
I couldn't install the linked .apk, either. It said that the package appears to be corrupt.

**Comment by nikolowry** [comment]
@paulijar I believe it's due to the APK being an unsigned release variant. Feel free to try the Debug apk I just built https://neeks.me/cloud/index.php/s/aHLYyfiMn6AL4nE

I also scanned Logcat and this warning seemed to be the relevant log:
```
[SettingsFragment]
java.io.IOException
java.io.IOException
	at net.nullsum.audinaut.service.parser.AbstractParser.handleError(AbstractParser.java:75)
	at net.nullsum.audinaut.service.parser.ErrorParser.parse(ErrorParser.java:44)
	at net.nullsum.audinaut.service.RESTMusicService.ping(RESTMusicService.java:86)
	at net.nullsum.audinaut.service.CachedMusicService.ping(CachedMusicService.java:73)
	at net.nullsum.audinaut.fragments.SettingsFragment$3.doInBackground(SettingsFragment.java:623)
	at net.nullsum.audinaut.fragments.SettingsFragment$3.doInBackground(SettingsFragment.java:611)
	at net.nullsum.audinaut.util.BackgroundTask$Task.execute(BackgroundTask.java:173)
	at net.nullsum.audinaut.util.BackgroundTask$Task.access$100(BackgroundTask.java:159)
	at net.nullsum.audinaut.util.BackgroundTask$TaskRunnable.run(BackgroundTask.java:269)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by paulijar** [comment]
@nikolowry Okay, thanks, I now managed to test your apk. I added some debug logging to my server, and I can see that Audinaut still tries to use the token+salt authentication, regardless of the new switch. So as far as I can see, the switch does nothing.

**Comment by nikolowry** [comment]
@paulijar the reason the switch was having no effect was because of this line https://github.com/dddddd-mmmmmm/Audinaut/commit/5141eb6e81929229a5204b00d72cd8c5bf016be6#diff-ba3ee5917f459d9f5af3cf6e941ed280R328, it instead should read:
```java
        if (prefs.getBoolean(Constants.PREFERENCES_KEY_AUTH_METHOD + instance, true)) {
```

I rebuilt and re-uploaded the Debug apk and it can be downloaded from the url I previously shared.

---

While I now can successfully connect, there seems to be a new issue in fetching data:
![Screenshot_20200113-162556_Audinaut](https://user-images.githubusercontent.com/597310/72294284-376f0780-3623-11ea-8bf8-6b7d1329343f.png)

Relevant logs from Logcat:
```
[Subsonic Activity]
Error on creating options menu
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object net.nullsum.audinaut.activity.SubsonicActivity.getSystemService(java.lang.String)' on a null object reference
	at net.nullsum.audinaut.fragments.SubsonicFragment.onFinishSetupOptionsMenu(SubsonicFragment.java:157)
	at net.nullsum.audinaut.fragments.SelectRecyclerFragment.onCreateOptionsMenu(SelectRecyclerFragment.java:104)
	at net.nullsum.audinaut.fragments.SelectArtistFragment.onCreateOptionsMenu(SelectArtistFragment.java:128)
	at net.nullsum.audinaut.activity.SubsonicActivity.onCreateOptionsMenu(SubsonicActivity.java:411)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3482)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

[SelectRecyclerView]
Failed to load
java.io.IOException
	at net.nullsum.audinaut.service.parser.AbstractParser.handleError(AbstractParser.java:75)
	at net.nullsum.audinaut.service.parser.IndexesParser.parse(IndexesParser.java:110)
	at net.nullsum.audinaut.service.RESTMusicService.getIndexes(RESTMusicService.java:122)
	at net.nullsum.audinaut.service.CachedMusicService.getIndexes(CachedMusicService.java:115)
	at net.nullsum.audinaut.fragments.SelectArtistFragment.getObjects(SelectArtistFragment.java:171)
	at net.nullsum.audinaut.fragments.SelectRecyclerFragment$UpdateTask.doInBackground(SelectRecyclerFragment.java:186)
	at net.nullsum.audinaut.fragments.SelectRecyclerFragment$UpdateTask.doInBackground(SelectRecyclerFragment.java:171)
	at net.nullsum.audinaut.util.BackgroundTask$Task.execute(BackgroundTask.java:173)
	at net.nullsum.audinaut.util.BackgroundTask$Task.access$100(BackgroundTask.java:159)
	at net.nullsum.audinaut.util.BackgroundTask$TaskRunnable.run(BackgroundTask.java:269)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by paulijar** [comment]
@nikolowry I downloaded the new apk, and for me, it's actually working. I can see the library and play songs. The "First level artists" option has to be ticked, or otherwise Audinaut can't show any albums when I open an artist. But this is the same when testing the app against the Subsonic demo server.

On your system, can you find anything interesting from ownlcoud.log or nextcloud.log on your server? You will get more detailed logs, if you set the logging level to "debug". This is possible through the web UI admin settings at least on some cloud versions, but it should work on all versions by editing the file `config/config.php`, and settings the value `'loglevel' => 0`.

**Comment by nikolowry** [comment]
@paulijar actually it's all working -- had to click "Go Online" in the sidebar nav.

Would love to see @dddddd-mmmmmm's changes make its way into the next release!

**Comment by dddddd-mmmmmm** [comment]
@paulijar @nikolowry That's great to hear, I'll open a PR.
